include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

stages:
  - test
  - deploy
  - dast

image: node:latest
cache:
  paths:
    - node_modules

test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run build
  only:
    - merge_requests

deploy:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master

dast:
  stage: dast
  variables:
    DAST_WEBSITE: https://polprzewodnikowy.gitlab.io/stream-watcher
  only:
    - master
