export const TWITCH_SAVE_TOKEN = 'TWITCH_SAVE_TOKEN';
export const TWITCH_SAVE_USER = 'TWITCH_SAVE_USER';
export const TWITCH_SAVE_FOLLOWED = 'TWITCH_SAVE_FOLLOWED';
export const TWITCH_SAVE_STREAMS = 'TWITCH_SAVE_STREAMS';
export const TWITCH_SAVE_GAMES = 'TWITCH_SAVE_GAMES';
export const TWITCH_SET_REFRESH_INTERVAL = 'TWITCH_SET_REFRESH_INTERVAL';
export const TWITCH_SET_CHANNEL = 'TWITCH_SET_CHANNEL';
export const TWITCH_SET_SHOW_CHAT_STATE = 'TWITCH_SET_SHOW_CHAT_STATE';
