name: Build and deploy app to GitHub Pages

on:
  push:	
    branches:	
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: PUBLIC_URL=${{ secrets.PUBLIC_URL }}; REACT_APP_TWITCH_CLIENT_ID=${{ secrets.REACT_APP_TWITCH_CLIENT_ID }}; npm install && npm run build
